### ISSUE TITLE
部署好了怎么使用，一直405

### ISSUE THREAD

**Issue by huangzhitian** [sherlcok314159/reverse-kimi#6]
文档没有说明模型叫什么，看了前面的问题填的 moonshot-v1
还有就是官网获取的两个token格式 是eyJh**********，comfig.json里面的Bearer是啥，我加和没加请求都不行
感谢回答
![QQ截图20240318232514](https://github.com/sherlcok314159/reverse-kimi/assets/129321746/0fec1c15-c401-4413-ba87-b29022b4100d)
![QQ截图20240318232532](https://github.com/sherlcok314159/reverse-kimi/assets/129321746/9810792b-576b-4f94-86a8-1ca207096255)
![QQ截图20240318232606](https://github.com/sherlcok314159/reverse-kimi/assets/129321746/b065035d-e471-436f-8f83-5c21d9b0fa72)
![QQ截图20240318234224](https://github.com/sherlcok314159/reverse-kimi/assets/129321746/1e1187a6-f132-4c63-9d37-620349f278b4)
![QQ截图20240318232641](https://github.com/sherlcok314159/reverse-kimi/assets/129321746/d4b14b86-26fb-474c-8d07-e6dab78be76d)

**Comment by sherlcok314159** [comment]
示例：

```yaml
- token: 'Bearer 123456' # config.json 中
- api_key: 'Bearer 123456' # 第三方 UI 中
- 模型名：'moonshot-v1'
```

关于 Bearer ，是一种鉴权输入格式，必须要有
